version: '{build}'

branches:
  only:
  - master

image:
- Visual Studio 2019

configuration:
- Debug
- Release

environment:
  matrix:
  - ARCHITECTURE: Win32
    GENERATOR: Visual Studio 16 2019
  - ARCHITECTURE: x64
    GENERATOR: Visual Studio 16 2019
      
build_script:
  - mkdir build_cmake
  - cd build_cmake
  - cmake -G "%GENERATOR%" -A %ARCHITECTURE% -S ".." -DCMAKE_BUILD_TYPE=%configuration%
  - cmake --build . --config %configuration%
  - cd ..